[package]
name = "moleengine"
version = "0.1.0"
authors = ["Mikael Myyrä <mikael.myyrae@gmail.com>"]
edition = "2018"

[dependencies]
winit = "0.22.0"
wgpu = "0.5.0"
zerocopy = "0.3.0"
futures = "0.3.4"
nalgebra = "0.21.0"
hibitset = "0.6.3"
anymap = "0.12.1"
lazy_static = "1.4.0"
serde = { features = ["derive"], version = "1.0.104" }
ron = "0.5.1"

[dev-dependencies]
microprofile = "0.2.1"
rand = "0.7.3"

[profile.dev]
opt-level = 1
