[package]
name = "starframe"
version = "0.1.0"
authors = ["Mikael Myyrä <mikael.myyrae@gmail.com>"]
edition = "2018"

[dependencies]
winit = "0.23.0"
wgpu = "0.8.1"
zerocopy = "0.3.0"
futures = "0.3.7"
ultraviolet = { version = "0.7.5", features = ["f64"] }
serde = { version = "1.0.104", features = ["derive"] }
ron = "0.6.2"
itertools = "0.9.0"
slotmap = "0.4.0"

[dev-dependencies]
microprofile = "0.2.1"
rand = "0.7.3"

[profile.dev]
opt-level = 1
