[package]
name = "moleengine"
version = "0.1.0"
authors = ["Mikael Myyrä <mikael.myyrae@gmail.com>"]
edition = "2018"

[dependencies]
glutin = "0.20.0"
nalgebra = "0.18.0"
hibitset = "0.5.4"
anymap = "0.12.1"
pest = "2.1.0"
pest_derive = "2.1.0"
parking_lot = "0.7.1"
lazy_static = "1.3.0"
shrinkwraprs = "0.2.1"

[dependencies.moleengine_ecs_codegen]
path = "./ecs_codegen"
optional = true

[dependencies.glium]
version = "0.24.0"
optional = true

[dev-dependencies]
microprofile = "0.1.0"
rand = "0.6.5"

[features]
ecs = ["moleengine_ecs_codegen"]
physics2d = []
visuals_glium = ["glium"]
debug_visuals = []

default = ["ecs", "physics2d", "visuals_glium"]
all = ["ecs", "physics2d", "visuals_glium", "debug_visuals"]

[[example]]
name = "testgame"
required-features = ["all"]
