[package]
name = "starframe"
version = "0.1.0"
authors = ["Mikael Myyrä <mikael.myyrae@gmail.com>"]
edition = "2018"

[dependencies]
winit = "0.25.0"
wgpu = "0.8.1"
zerocopy = "0.5.0"
futures = "0.3.15"
ultraviolet = { version = "0.8.0", features = ["f64"] }
serde = { version = "1.0.126", features = ["derive"] }
ron = "0.6.4"
itertools = "0.10.0"
slotmap = "1.0.3"

[dev-dependencies]
microprofile = "0.2.1"
rand = "0.7.3"

[profile.dev]
opt-level = 1
