[package]
name = "moleengine"
version = "0.1.0"
authors = ["Mikael Myyrä <mikael.myyrae@gmail.com>"]
edition = "2018"

[dependencies]
glutin = "0.21.0"
nalgebra = "0.18.0"
hibitset = "0.6.2"
anymap = "0.12.1"
parking_lot = "0.9.0"
lazy_static = "1.3.0"
shrinkwraprs = "0.2.1"
moleengine_ecs_codegen = { optional = true, path = "./ecs_codegen" }
glium = { optional = true, version = "0.25.1" }
serde = { optional = true, features = ["derive"], version = "1.0.99" }
ron = { optional = true, version = "0.5.1" }

[dev-dependencies]
microprofile = "0.2.1"
rand = "0.7.0"

[features]
ecs = ["moleengine_ecs_codegen", "serde"]
ron-recipes = ["ecs", "nalgebra/serde-serialize", "serde", "ron"]
physics2d = []
visuals_glium = ["glium"]
debug_visuals = []

default = ["ecs", "ron-recipes", "physics2d", "visuals_glium"]
all = ["ecs", "ron-recipes", "physics2d", "visuals_glium", "debug_visuals"]

[[example]]
name = "testgame"
required-features = ["all"]

[profile.dev]
opt-level = 1
