[package]
name = "moleengine_visuals"
version = "0.1.0"
authors = ["Mikael Myyrä <mikael.myyrae@gmail.com>"]
edition = "2018"

[dependencies]
piston = "0.37.0"
piston2d-graphics = "0.26.0"
moleengine_ecs = { path = "../ecs" }
moleengine_core = { path = "../core" }
