[package]
name = "moleengine_physics"
version = "0.1.0"
authors = ["Mikael Myyrä <mikael.myyrae@gmail.com>"]
edition = "2018"

[dependencies]
moleengine = { path = "../core" }
piston2d-graphics = "0.30"
nalgebra = "0.17.2"
