[package]
name = "moleengine_core"
version = "0.1.0"
authors = ["Mikael Myyrä <mikael.myyrae@gmail.com>"]
edition = "2018"

[dependencies]
piston = "0.40"
piston2d-graphics = "0.30"
pistoncore-glutin_window = "0.52"
piston2d-opengl_graphics = "0.59"
nalgebra = "0.16"
